let Item = [
	{
		key: 0,
		itemId: 0, 
		userId: 0, 
		seller: 'Pokemon Go', 
		name: 'Orange Crystal Ball', 
		sellable: true,
		cost: '1.99',
		currency: 'USD',
		amount: '50',
		owner: 'developer',
		url: 'https://s3.amazonaws.com/robochild.com/images/orange_crystal_ball.png'
	},
	{
		key: 1,
		itemId: 0, 
		userId: 4, 
		seller: 'Roboberta', 
		name: 'Orange Crystal Ball', 
		sellable: true,
		cost: '.99',
		currency: 'USD',
		amount: '10',
		owner: 'player',
		url: 'https://s3.amazonaws.com/robochild.com/images/orange_crystal_ball.png'
	},
	{
		key: 2,
		itemId: 0, 
		userId: 5, 
		seller: 'Alberta', 
		name: 'Orange Crystal Ball', 
		sellable: true,
		cost: '.99',
		currency: 'USD',
		amount: '20',
		owner: 'player',
		url: 'https://s3.amazonaws.com/robochild.com/images/orange_crystal_ball.png'
	},
	{
		key: 3,
		itemId: 1, 
		userId: 0, 
		seller: 'Pokemon Go', 
		name: 'Purple Crystal Ball', 
		sellable: true,
		cost: '.99',
		currency: 'USD',
		amount: '50',
		owner: 'developer',
		url: 'https://s3.amazonaws.com/robochild.com/images/purple_crystal_ball.png'
	},
	{
		key: 4,
		itemId: 2, 
		userId: 1, 
		seller: 'Candy Crush', 
		name: 'Strawberry', 
		sellable: true,
		cost: '.99',
		currency: 'USD',
		amount: '50',
		owner: 'developer',
		url: 'https://s3.amazonaws.com/robochild.com/images/strawberry.png'
	},
	{
		key: 5,
		itemId: 3, 
		userId: 1, 
		seller: 'Candy Crush', 
		name: 'Banana', 
		sellable: true,
		cost: '.99',
		currency: 'USD',
		amount: '50',
		owner: 'developer',
		url: 'https://s3.amazonaws.com/robochild.com/images/banana.png'
	},
	{
		key: 6,
		itemId: 4, 
		userId: 1, 
		seller: 'Candy Crush', 
		name: 'Watermelon', 
		sellable: true,
		cost: '.99',
		currency: 'USD',
		amount: '50',
		owner: 'developer',
		url: 'https://s3.amazonaws.com/robochild.com/images/watermelon.png'
	},
	{
		key: 7,
		itemId: 5, 
		userId: 2, 
		seller: 'Bejeweled', 
		name: 'Ruby Gem', 
		sellable: true,
		cost: '.99',
		currency: 'USD',
		amount: '50',
		owner: 'developer',
		url: 'https://s3.amazonaws.com/robochild.com/images/ruby_gem.png'
	},
	{
		key: 8,
		itemId: 6, 
		userId: 2, 
		seller: 'Bejeweled',
		name: 'Yellow Gem', 
		sellable: true,
		cost: '.99',
		currency: 'USD',
		amount: '50',
		owner: 'developer',
		url: 'https://s3.amazonaws.com/robochild.com/images/yellow_gem.png'
	}
]

module.exports = Item;